### ISSUE TITLE
Latest tag broke my container

### ISSUE THREAD

**Issue by badams** [coppit/docker-xeoma#6]
Hi,
Since about an hour ago my xeoma container tried to update itself and wont come back up, nothing notable in the logs, but it happened as soon as you pushed the new tag to docker hub, are having any issues on your end @coppit?

```
xeoma    | Configuration:
xeoma    |   PASSWORD=<hidden>
xeoma    |   VERSION=latest
xeoma    | 2018-08-16 02:25:48 Determining version of Xeoma to use
xeoma    | 2018-08-16 02:25:48 Config version is "latest"
xeoma    | 2018-08-16 02:25:48 Fetching version information from Felenasoft at http://felenasoft.com/xeoma/downloads/version2.xml
xeoma    | 2018-08-16 02:25:48 Using Xeoma version 18.7.10 (the latest stable version)
xeoma    | 2018-08-16 02:25:48 Downloaded file /config/downloads/xeoma_18.7.10.tgz already exists. Skipping download
xeoma    | 2018-08-16 02:25:48 Skipping installation because the currently installed version is the correct one
xeoma    | [Aug 16 02:25:48] Setting the password
xeoma    |
xeoma    |
xeoma    | Password set successfull
xeoma    | Started runsvdir, PID is 54. Waiting for processes to start....
xeoma    | [Aug 16 02:25:49] Starting the server in 5 seconds. See the log directory in your config directory for server logs.
xeoma    | run: cron: (pid 58) 5s
xeoma    | run: xeoma: (pid 59) 5s
```

**Comment by skylord123** [comment]
Having the same issue. Logs are identical.

**Comment by skylord123** [comment]
@coppit I recommend using versioning for your updates you do to this project. That way we can just use the older version when updates like this break.

I built the project and reset the last 2 commits which seemed to fix the issue for me. I did this for now because I need my cameras functioning (don't know when the fix will be available). If others run into this issue and just want to get it working until @coppit is able to resolve the issue just change your repository to `skylord123/xeoma` and change it back when it is resolved.

**Comment by badams** [comment]
Agreed the builds should triggered by a release on github rather than pushing to master.

I've also done the same as @skylord123 suggested in the mean time

**Comment by coppit** [comment]
Should be fixed now.

I'll consider adding build versioning. I thought docker hub allowed you to see the digest ID for the old builds, but I guess not. It only shows a partial ID:

`Successfully built 51aa745ed9d6`

**Comment by skylord123** [comment]
@coppit I am still having the issue. I am running docker containers under unRAID. I updated to the latest version. I also tried removing the image completely and re-adding it to no avail.

EDIT: I had to revert back to my repository for now which is still working as a fix.

```
Configuration:
PASSWORD=<hidden>
VERSION=http://felenasoft.com/xeoma/downloads/xeoma_beta_linux64.tgz

2018-08-17 04:01:12 Determining version of Xeoma to use

2018-08-17 04:01:12 Config version is "http://felenasoft.com/xeoma/downloads/xeoma_beta_linux64.tgz"

2018-08-17 04:01:12 Using Xeoma version from url (http://felenasoft.com/xeoma/downloads/xeoma_beta_linux64.tgz)

2018-08-17 04:01:12 Downloaded file /config/downloads/xeoma_from_url.tgz already exists. Skipping download
2018-08-17 04:01:12 Installing Xeoma from /config/downloads/xeoma_from_url.tgz
2018-08-17 04:01:13 Installation complete
[Aug 17 04:01:14] Setting the password


Password set successfull
Started runsvdir, PID is 56. Waiting for processes to start....
[Aug 17 04:01:14] Starting the server in 5 seconds. See the log directory in your config directory for server logs.
run: cron: (pid 60) 5s
run: xeoma: (pid 61) 5s
```

**Comment by coppit** [comment]
Okay, I found and fixed another issue, and tested it to make sure it updates okay.

What threw me is that the issue I fixed has been there for a while, and it unrelated to the changes I made in the last couple of days.

Please test and confirm the fix.

**Comment by badams** [comment]
Hi @coppit thanks for taking time to look at this,

Still no luck upgrading on my end with that latest push

```
Configuration:


  PASSWORD=<hidden>


  VERSION=latest


2018-08-18 00:08:49 Determining version of Xeoma to use


2018-08-18 00:08:49 Config version is "latest"


2018-08-18 00:08:49 Fetching version information from Felenasoft at http://felenasoft.com/xeoma/downloads/version2.xml


2018-08-18 00:08:50 Using Xeoma version 18.7.10 (the latest stable version)


2018-08-18 00:08:50 Downloaded file /config/downloads/xeoma_18.7.10.tgz already exists. Skipping download


2018-08-18 00:08:50 Installing Xeoma from /config/downloads/xeoma_18.7.10.tgz


2018-08-18 00:08:51 Installation complete


[Aug 18 00:08:51] Setting the password






Password set successfull


Started runsvdir, PID is 56. Waiting for processes to start....


[Aug 18 00:08:51] Starting the server in 5 seconds. See the log directory in your config directory for server logs.


run: cron: (pid 61) 5s


run: xeoma: (pid 60) 5s

```

**Comment by coppit** [comment]
That log looks totally normal. But you say that the container isn't running afterwards?

**Comment by badams** [comment]
Correct the process is not running after that, there are no errors in the log but I assume that is because the xeoma process is not running in foreground

**Comment by badams** [comment]
@coppit I decided to test creating a new container for this without using my existing config dir

docker-compose.yml
```
version: "2"
services:
  xeoma:
    image: coppit/xeoma
    container_name: xeoma
    networks:
      - local
    volumes:
       - /mediabox/config/xeoma_test:/config
    restart: unless-stopped
    ports:
      - "8090:8090"
networks:
  local:
    external:
      name: mediabox_local
```

```
mediabox@mediabox:/mediabox/docker/cctv$ docker-compose up
Creating xeoma
Attaching to xeoma
xeoma    | /etc/run_once/30_parse_config_file: line 82: Creating: No such file or directory
xeoma    | grep: Creating: No such file or directory
xeoma    | declare -x HOME="/root"
xeoma    | declare -x HOSTNAME="90684c5a514e"
xeoma    | declare -x OLDPWD
xeoma    | declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
xeoma    | declare -x PWD="/"
xeoma    | declare -x SHLVL="1"
xeoma    | declare -x TERM="xterm-256color"
xeoma    | Missing required settings, which must be provided in the config file or by environment variables:
xeoma    | PASSWORD
xeoma    | 2018-08-18 02:21:45 Determining version of Xeoma to use
xeoma    | /bin/bash: /etc/envvars.merged: No such file or directory
xeoma    | 2018-08-18 02:21:45 Config version is ""
xeoma    | 2018-08-18 02:21:45 Fetching version information from Felenasoft at http://felenasoft.com/xeoma/downloads/version2.xml
xeoma    | 2018-08-18 02:21:45 Using Xeoma version 18.7.10 (the latest stable version)
xeoma    | 2018-08-18 02:21:45 Deleting files in /config/downloads to reclaim space...
xeoma    | 2018-08-18 02:21:45 Downloading from http://felenasoft.com/xeoma/downloads/xeoma_linux64.tgz into /config/downloads
xeoma    | 2018-08-18 02:21:45 Downloading from http://felenasoft.com/xeoma/downloads/xeoma_linux64.tgz
xeoma    | 2018-08-18 02:22:09 Downloaded to /config/downloads/xeoma_18.7.10.tgz
xeoma    | 2018-08-18 02:22:09 Installing Xeoma from /config/downloads/xeoma_18.7.10.tgz
xeoma    | 2018-08-18 02:22:10 Installation complete
xeoma    | /etc/run_once/50_configure_xeoma: line 7: /etc/envvars.merged: No such file or directory
xeoma    | [Aug 18 02:22:10] Setting the password
xeoma    | Failed to open 'libX11'
xeoma    | Failed to open 'libX11'
xeoma    |  ! XWindow graphical shell is not available in console mode
xeoma    |  ! You must run Xeoma with available parameters, i.e. to run server: -core
xeoma    |  ! Type '-help' for read parameters list.
xeoma    |
xeoma    | Started runsvdir, PID is 49. Waiting for processes to start....
xeoma    | [Aug 18 02:22:11] Starting the server in 5 seconds. See the log directory in your config directory for server logs.
xeoma    | run: cron: (pid 54) 5s
xeoma    | run: xeoma: (pid 53) 5s
^CGracefully stopping... (press Ctrl+C again to force)
```

I then stopped the container and tried to enter a password into the xeoma.conf file and start it again
```
mediabox@mediabox:/mediabox/docker/cctv$ docker-compose up
Starting xeoma
Attaching to xeoma
xeoma    | Configuration:
xeoma    |   PASSWORD=<hidden>
xeoma    |   VERSION=latest
xeoma    | 2018-08-18 02:23:28 Determining version of Xeoma to use
xeoma    | 2018-08-18 02:23:28 Config version is "latest"
xeoma    | 2018-08-18 02:23:28 Fetching version information from Felenasoft at http://felenasoft.com/xeoma/downloads/version2.xml
xeoma    | 2018-08-18 02:23:28 Using Xeoma version 18.7.10 (the latest stable version)
xeoma    | 2018-08-18 02:23:28 Downloaded file /config/downloads/xeoma_18.7.10.tgz already exists. Skipping download
xeoma    | 2018-08-18 02:23:28 Skipping installation because the currently installed version is the correct one
xeoma    | [Aug 18 02:23:28] Setting the password
xeoma    |
xeoma    |
xeoma    | Password set successfull
xeoma    | Started runsvdir, PID is 54. Waiting for processes to start....
xeoma    | [Aug 18 02:23:29] Starting the server in 5 seconds. See the log directory in your config directory for server logs.
xeoma    | run: cron: (pid 59) 5s
xeoma    | run: xeoma: (pid 58) 5s
```

Everything looks normal but its not running

**Comment by coppit** [comment]
Okay, I've reverted all the recent changes to get you back in business. I'll try to figure it out before moving forward with Alpine. The build is happening now and should be ready in a few minutes.

**Comment by badams** [comment]
Thanks @coppit
